FROM logstash:7.9.0

USER root

COPY logstash.conf /usr/share/logstash/bin/logstash.conf

CMD /usr/share/logstash/bin/logstash -f /usr/share/logstash/bin/logstash.conf --path.settings /etc/logstash2 --path.data sensor39

