apiVersion: v1
kind: Service
metadata:
  name: mission-node-port
spec:
  type: NodePort
  ports:
    - name: elasticsearch
      port: 9200
      targetPort: 9200
      nodePort: 30000
    - name: logstash
      port: 5044
      targetPort: 5044
      nodePort: 30001
    - name: kibana
      port: 5601 
      targetPort: 5601
      nodePort: 30002
    - name: filebeat
      port: 5045
      targetPort: 5044
      nodePort: 30003
  selector:
    component: elk